### PR TITLE
update deps

### LINKED ISSUE #9: Cant build on node.js v16
## Expected Behavior
I should be able to build this library

## Current Behavior
It does not build

## Possible Solution

--

## Steps to Reproduce

1. On node v16
2. run `npm build`

## Context (Environment)
```
❯ npm run-script configure 

> boost-geospatial-index@1.1.0 configure
> node-gyp configure

gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.0
gyp info using node@16.15.0 | linux | x64
gyp info find Python using Python version 3.10.4 found at "/bin/python3"
(node:23292) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /bin/python3
gyp info spawn args [
gyp info spawn args   '/tmp/boost-geospatial-index/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/boost-geospatial-index/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/boost-geospatial-index/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pedro/.cache/node-gyp/16.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pedro/.cache/node-gyp/16.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/tmp/boost-geospatial-index/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pedro/.cache/node-gyp/16.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/tmp/boost-geospatial-index',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/tmp/boost-geospatial-index/node_modules/node-gyp/gyp/gyp_main.py", line 47, in <module>
    import gyp
  File "/tmp/boost-geospatial-index/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 10, in <module>
    import gyp.input
  File "/tmp/boost-geospatial-index/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 9, in <module>
    import gyp.common
  File "/tmp/boost-geospatial-index/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 499, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/tmp/boost-geospatial-index/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.15.41_1
gyp ERR! command "/home/pedro/.nvm/versions/node/v16.15.0/bin/node" "/tmp/boost-geospatial-index/node_modules/.bin/node-gyp" "configure"
gyp ERR! cwd /tmp/boost-geospatial-index
gyp ERR! node -v v16.15.0
gyp ERR! node-gyp -v v6.0.0
gyp ERR! not ok 
```

### PR DESCRIPTION
**Pull request by revington**
## What does this PR do ?
Fix #9. Can't build on node v16.
I've just run npm update on node v16.15 and npm v8.5.5. Then it build as expected.

### CODE REVIEW

**Comment by revington** [comment]
Hey, could you please check this out? 
If there is anything else on my side to move this forward just tell me.

**Comment by Aschen** [comment]
Hello @revington !

I'm able to build this package with Node.js 16:

```
$ docker run -it kuzzleio/kuzzle-runner:16 npm i boost-geospatial-index

added 4 packages, and audited 5 packages in 20s

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 8.11.0 -> 8.14.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.14.0
npm notice Run npm install -g npm@8.14.0 to update!
npm notice
```

I see that your PR only update the package-lock.json but this file is not even included in the distributed package so I don't see how it could fix the build.

Can you provide more information about what you are trying to achieve?

**Comment by Aschen** [comment]
@revington Were you on MacOs ? We had the same issue and we fixed it in https://github.com/kuzzleio/boost-geospatial-index/pull/11

We cannot upgrade the package-lock.json to the `lockFile` version 2 because it will break the compatibility with Node.js 14

**Comment by revington** [comment]
Hey @Aschen,

Sorry for a late reply. We were able to reproduce it on both Linux and MacOS (M1). I'm not able to reproduce it again on Linux. Maybe I've just updated `npm`.

**Comment by yasmanets** [comment]
Hi @Aschen 
I have a Mac M1 and when I try to install the package I get the following error:

```bash
npm ERR! code 1
npm ERR! path /Users/yaser/Desktop/test/node_modules/boost-geospatial-index
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CXX(target) Release/obj.target/BoostSpatialIndex/src/shape.o
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@18.3.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.8.9 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
npm ERR! gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/yaser/.nvm/versions/node/v18.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/yaser/Desktop/test/node_modules/boost-geospatial-index/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/yaser/.nvm/versions/node/v18.3.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/yaser/Library/Caches/node-gyp/18.3.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/yaser/Library/Caches/node-gyp/18.3.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/yaser/.nvm/versions/node/v18.3.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/yaser/Library/Caches/node-gyp/18.3.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/yaser/Desktop/test/node_modules/boost-geospatial-index',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/shape.cc:1:
npm ERR! In file included from ../src/shape.hpp:5:
npm ERR! In file included from ../include/boost/geometry.hpp:17:
npm ERR! In file included from ../include/boost/geometry/geometry.hpp:50:
npm ERR! In file included from ../include/boost/geometry/strategies/strategies.hpp:32:
npm ERR! In file included from ../include/boost/geometry/strategies/intersection_strategies.hpp:20:
npm ERR! In file included from ../include/boost/geometry/policies/relate/intersection_points.hpp:20:
npm ERR! In file included from ../include/boost/geometry/algorithms/detail/assign_indexed_point.hpp:21:
npm ERR! In file included from ../include/boost/geometry/algorithms/detail/assign_values.hpp:28:
npm ERR! In file included from ../include/boost/geometry/algorithms/append.hpp:30:
npm ERR! In file included from ../include/boost/geometry/algorithms/num_interior_rings.hpp:36:
npm ERR! In file included from ../include/boost/geometry/algorithms/detail/counting.hpp:30:
npm ERR! ../include/boost/geometry/util/range.hpp:376:19: warning: 'iterator<std::output_iterator_tag, void, void, void, void>' is deprecated [-Wdeprecated-declarations]
npm ERR!     : public std::iterator<std::output_iterator_tag, void, void, void, void>
npm ERR!                   ^
npm ERR! /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__iterator/iterator.h:27:29: note: 'iterator<std::output_iterator_tag, void, void, void, void>' has been explicitly marked deprecated here
npm ERR! struct _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 iterator
npm ERR!                             ^
npm ERR! /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:1066:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
npm ERR! #  define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
npm ERR!                                       ^
npm ERR! /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:1043:48: note: expanded from macro '_LIBCPP_DEPRECATED'
npm ERR! #    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
npm ERR!                                                ^
npm ERR! In file included from ../src/shape.cc:1:
npm ERR! In file included from ../src/shape.hpp:5:
npm ERR! In file included from ../include/boost/geometry.hpp:17:
npm ERR! In file included from ../include/boost/geometry/geometry.hpp:50:
npm ERR! In file included from ../include/boost/geometry/strategies/strategies.hpp:32:
npm ERR! In file included from ../include/boost/geometry/strategies/intersection_strategies.hpp:30:
npm ERR! In file included from ../include/boost/geometry/strategies/spherical/intersection.hpp:33:
npm ERR! In file included from ../include/boost/geometry/policies/robustness/segment_ratio.hpp:17:
npm ERR! In file included from ../include/boost/rational.hpp:77:
npm ERR! ../include/boost/operators.hpp:840:10: warning: 'iterator<std::output_iterator_tag, void, void, void, void>' is deprecated [-Wdeprecated-declarations]
npm ERR!   , std::iterator<std::output_iterator_tag, void, void, void, void
npm ERR!          ^
npm ERR! /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__iterator/iterator.h:27:29: note: 'iterator<std::output_iterator_tag, void, void, void, void>' has been explicitly marked deprecated here
npm ERR! struct _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 iterator
npm ERR!                             ^
npm ERR! /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:1066:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
npm ERR! #  define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
npm ERR!                                       ^
npm ERR! /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:1043:48: note: expanded from macro '_LIBCPP_DEPRECATED'
npm ERR! #    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
npm ERR!                                                ^
npm ERR! In file included from ../src/shape.cc:1:
npm ERR! In file included from ../src/shape.hpp:5:
npm ERR! In file included from ../include/boost/geometry.hpp:17:
npm ERR! In file included from ../include/boost/geometry/geometry.hpp:50:
npm ERR! In file included from ../include/boost/geometry/strategies/strategies.hpp:40:
npm ERR! In file included from ../include/boost/geometry/strategies/cartesian/buffer_end_round.hpp:25:
npm ERR! In file included from ../include/boost/geometry/io/wkt/wkt.hpp:17:
npm ERR! In file included from ../include/boost/geometry/io/wkt/read.hpp:28:
npm ERR! In file included from ../include/boost/algorithm/string.hpp:23:
npm ERR! In file included from ../include/boost/algorithm/string/split.hpp:16:
npm ERR! In file included from ../include/boost/algorithm/string/iter_find.hpp:27:
npm ERR! In file included from ../include/boost/algorithm/string/find_iterator.hpp:24:
npm ERR! In file included from ../include/boost/algorithm/string/detail/find_iterator.hpp:18:
npm ERR! In file included from ../include/boost/function.hpp:24:
npm ERR! In file included from ../include/boost/function/detail/prologue.hpp:18:
npm ERR! In file included from ../include/boost/mem_fn.hpp:22:
npm ERR! In file included from ../include/boost/bind/mem_fn.hpp:25:
npm ERR! ../include/boost/get_pointer.hpp:48:23: error: redefinition of 'get_pointer' as different kind of symbol
npm ERR! template<class T> T * get_pointer(std::auto_ptr<T> const& p)
npm ERR!                       ^
npm ERR! ../include/boost/get_pointer.hpp:20:23: note: previous definition is here
npm ERR! template<class T> T * get_pointer(T * p)
npm ERR!                       ^
npm ERR! ../include/boost/get_pointer.hpp:48:40: error: no member named 'auto_ptr' in namespace 'std'
npm ERR! template<class T> T * get_pointer(std::auto_ptr<T> const& p)
npm ERR!                                   ~~~~~^
npm ERR! ../include/boost/get_pointer.hpp:48:49: error: 'T' does not refer to a value
npm ERR! template<class T> T * get_pointer(std::auto_ptr<T> const& p)
npm ERR!                                                 ^
npm ERR! ../include/boost/get_pointer.hpp:48:16: note: declared here
npm ERR! template<class T> T * get_pointer(std::auto_ptr<T> const& p)
npm ERR!                ^
npm ERR! ../include/boost/get_pointer.hpp:48:52: error: expected expression
npm ERR! template<class T> T * get_pointer(std::auto_ptr<T> const& p)
npm ERR!                                                    ^
npm ERR! ../include/boost/get_pointer.hpp:48:61: error: expected ';' at end of declaration
npm ERR! template<class T> T * get_pointer(std::auto_ptr<T> const& p)
npm ERR!                                                             ^
npm ERR!                                                             ;
npm ERR! ../include/boost/get_pointer.hpp:49:1: error: expected unqualified-id
npm ERR! {
npm ERR! ^
npm ERR! In file included from ../src/shape.cc:1:
npm ERR! In file included from ../src/shape.hpp:5:
npm ERR! In file included from ../include/boost/geometry.hpp:17:
npm ERR! In file included from ../include/boost/geometry/geometry.hpp:55:
npm ERR! In file included from ../include/boost/geometry/algorithms/buffer.hpp:36:
npm ERR! In file included from ../include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp:30:
npm ERR! In file included from ../include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp:27:
npm ERR! In file included from ../include/boost/geometry/algorithms/comparable_distance.hpp:23:
npm ERR! In file included from ../include/boost/geometry/algorithms/detail/comparable_distance/implementation.hpp:22:
npm ERR! In file included from ../include/boost/geometry/algorithms/detail/distance/implementation.hpp:25:
npm ERR! In file included from ../include/boost/geometry/algorithms/detail/distance/multipoint_to_geometry.hpp:26:
npm ERR! In file included from ../include/boost/geometry/algorithms/detail/distance/range_to_geometry_rtree.hpp:25:
npm ERR! In file included from ../include/boost/geometry/algorithms/detail/closest_feature/range_to_range.hpp:22:
npm ERR! In file included from ../include/boost/geometry/index/rtree.hpp:78:
npm ERR! ../include/boost/geometry/index/inserter.hpp:24:17: warning: 'iterator<std::output_iterator_tag, void, void, void, void>' is deprecated [-Wdeprecated-declarations]
npm ERR!     public std::iterator<std::output_iterator_tag, void, void, void, void>
npm ERR!                 ^
npm ERR! /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__iterator/iterator.h:27:29: note: 'iterator<std::output_iterator_tag, void, void, void, void>' has been explicitly marked deprecated here
npm ERR! struct _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 iterator
npm ERR!                             ^
npm ERR! /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:1066:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
npm ERR! #  define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
npm ERR!                                       ^
npm ERR! /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:1043:48: note: expanded from macro '_LIBCPP_DEPRECATED'
npm ERR! #    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
npm ERR!                                                ^
npm ERR! In file included from ../src/shape.cc:1:
npm ERR! In file included from ../src/shape.hpp:5:
npm ERR! In file included from ../include/boost/geometry.hpp:17:
npm ERR! In file included from ../include/boost/geometry/geometry.hpp:55:
npm ERR! In file included from ../include/boost/geometry/algorithms/buffer.hpp:36:
npm ERR! In file included from ../include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp:30:
npm ERR! In file included from ../include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp:27:
npm ERR! In file included from ../include/boost/geometry/algorithms/comparable_distance.hpp:23:
npm ERR! In file included from ../include/boost/geometry/algorithms/detail/comparable_distance/implementation.hpp:22:
npm ERR! In file included from ../include/boost/geometry/algorithms/detail/distance/implementation.hpp:25:
npm ERR! In file included from ../include/boost/geometry/algorithms/detail/distance/multipoint_to_geometry.hpp:26:
npm ERR! In file included from ../include/boost/geometry/algorithms/detail/distance/range_to_geometry_rtree.hpp:25:
npm ERR! In file included from ../include/boost/geometry/algorithms/detail/closest_feature/range_to_range.hpp:22:
npm ERR! In file included from ../include/boost/geometry/index/rtree.hpp:83:
npm ERR! In file included from ../include/boost/geometry/index/detail/rtree/query_iterators.hpp:14:
npm ERR! In file included from ../include/boost/scoped_ptr.hpp:14:
npm ERR! ../include/boost/smart_ptr/scoped_ptr.hpp:74:31: error: no template named 'auto_ptr' in namespace 'std'
npm ERR!     explicit scoped_ptr( std::auto_ptr<T> p ) BOOST_NOEXCEPT : px( p.release() )
npm ERR!                          ~~~~~^
npm ERR! In file included from ../src/shape.cc:1:
npm ERR! In file included from ../src/shape.hpp:5:
npm ERR! In file included from ../include/boost/geometry.hpp:17:
npm ERR! In file included from ../include/boost/geometry/geometry.hpp:50:
npm ERR! In file included from ../include/boost/geometry/strategies/strategies.hpp:32:
npm ERR! In file included from ../include/boost/geometry/strategies/intersection_strategies.hpp:22:
npm ERR! In file included from ../include/boost/geometry/policies/relate/tupled.hpp:15:
npm ERR! In file included from ../include/boost/tuple/tuple.hpp:28:
npm ERR! ../include/boost/tuple/detail/tuple_basic.hpp:400:9: warning: definition of implicit copy constructor for 'cons<boost::geometry::de9im::mask, boost::tuples::null_type>' is deprecated because it has a user-provided copy assignment operator [-Wdeprecated-copy-with-user-provided-copy]
npm ERR!   cons& operator=(const cons& u) { head = u.head; return *this; }
npm ERR!         ^
npm ERR! ../include/boost/tuple/detail/tuple_basic.hpp:294:17: note: in implicit copy constructor for 'boost::tuples::cons<boost::geometry::de9im::mask, boost::tuples::null_type>' first required here
npm ERR!     : head (h), tail(t) {}
npm ERR!                 ^
npm ERR! ../include/boost/geometry/algorithms/detail/relate/de9im.hpp:200:12: note: in instantiation of member function 'boost::tuples::cons<boost::geometry::de9im::mask, boost::tuples::cons<boost::geometry::de9im::mask, boost::tuples::null_type>>::cons' requested here
npm ERR!     return bt::cons<mask, bt::cons<mask, bt::null_type> >
npm ERR!            ^
npm ERR! 4 warnings and 7 errors generated.
npm ERR! make: *** [Release/obj.target/BoostSpatialIndex/src/shape.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/yaser/.nvm/versions/node/v18.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.5.0
npm ERR! gyp ERR! command "/Users/yaser/.nvm/versions/node/v18.3.0/bin/node" "/Users/yaser/.nvm/versions/node/v18.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/yaser/Desktop/test/node_modules/boost-geospatial-index
npm ERR! gyp ERR! node -v v18.3.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok
```

**Comment by yasmanets** [comment]
Hi again @Aschen 
In node v16 the package installs without problems.

**Comment by Aschen** [comment]
> Hi again @Aschen In node v16 the package installs without problems.

Yes we do not support Node.js 18 officially since some of our dependencies does not support it. I guess it will be fixed when the 18 will be in LTS.

**Comment by revington** [comment]
In https://github.com/kuzzleio/boost-geospatial-index/pull/13 I keep the lockfile at version 1

**Pull request closed without merging**
